### ISSUE TITLE
does it always use the preprocessing, i.e. "scale:"

### ISSUE THREAD

**Issue by genewitch** [nidhaloff/igel#34]
* igel version: pip
* Python version: 3.8.6
* Operating System: windows

### Description
I am just messing around, loaded a CSV with two columns, number (1-12,000,000) and prime (0 or 1)
the prime column was factual, a 1 means prime, a zero means composite.
I tried NeuralNetwork and CalibratedClassifier, but i think the preprocessing "scale:" messed it up. 
that is, the predictions.csv output for input csv single column numbers 3000-4000 i'd expect values other than 0.0, 
but all that is in there is 3000,0.0, 3001,0.0, and so on, every prediction is 0.0.

It takes a long time to generate the csvs (on my side) and to run the igel -DP suite, so i wanted to clear this up. 
P.S. I really appreciate all the work, i just kinda don't really understand, i think.

If i can help or ever can submit a PR or anything i'd be happy to!

**Comment by genewitch** [comment]
i deleted the "scale:" section and boy howdy does it take a long time for the "fit" command now. It's been running about 10 times as long as it did before already. I guess i answered my own question.

**Comment by nidhaloff** [comment]
Hi, I'm not sure I get it. Can you provide more details like for e.g are you using regression or classification and which options are you using?  do you mean that you get 2 values as output? 
Can you provide your yaml configurations ?

If you scale the values, it's normal that it will run faster. Of course you can omit the scale option if you don't want to use it.

if you have 12,000,000 data points in your dataset, then sure it will take longer since the algorithm is counting prediction for each data point and you have 12m that's quite a lot.

**Comment by genewitch** [comment]
it's pretty magical, actually. I got it working, and managed to get NeuralNetwork Classifier to do 0 false positives. I had to split the integers into decimal parts, 1000s, 100s, 10s, 1s, etc. It works fine now. I am closing, it was my misunderstanding of the inputs of the sklearn and some other options. I uploaded my scaffolding to my github under the "machinelearning" repo.

**Comment by genewitch** [comment]
This is probably the most fun i've had programming (ironic) in several months, thanks!

nn.yaml

```
dataset:
  read_data_options:
    header: 0
  type: csv
  true_values: 1
  false_values: 0
model:
  algorithm: NeuralNetwork
  arguments: "hidden_layer_sizes=(97,53,31,11,5,)"
  type: classification
  #use_cv_estimator: true
  #cross_validate:
  #  n_jobs: 16
  #  verbose: 1
target:
- prime
```

csv output from my scaffolding (in python): 
```
"10000","1000","100","10","1",prime
-1,-1,-1,-1,3,1
-1,-1,-1,-1,4,0
-1,-1,-1,-1,5,1
-1,-1,-1,-1,6,0
-1,-1,-1,-1,7,1
-1,-1,-1,-1,8,0
-1,-1,-1,-1,9,0
[...]
9,9,9,8,7,0
9,9,9,8,8,0
9,9,9,8,9,1
9,9,9,9,0,0
9,9,9,9,1,1
9,9,9,9,2,0
9,9,9,9,3,0
```
